@startuml
'https://plantuml.com/activity-diagram-beta


|Kunde|
start
:Vælg egne mål for carport;
if(Skur) then (Ja)
:Vælg mål/placering for skur;
else (Nej)
endif
:Indsend forespørgsel;
|Shop|
:Forespørgsel]
|Mailsystem|
:Send mail til sælger med forespørgsel;
|Sælger|
:Mail til sælger]
|Tilbudsberegning|
:Udfyld tilbudsberegning;
if (Komplikationer?) is (yes) then
|Telefonisk|
:Ring til kunde;
:Spørg om komplikationer;
:Ret tilbudsberegning;
else (no)
endif
|Sælger|
:Tilbudsberegning]
:Send tilbud til kunde;
|Kunde|
:Tilbud]
if (Accepter tilbud?) is (yes) then
|Sælger|
:Accepteret tilbud]
:Opret og send faktura til kunde;
|Kunde|
:Faktura]
:Betaling;
|Shop|
:Betaling]
|Sælger|
:Opret stykliste og send til kunde;

|Kunde|
:Stykliste]
:Vælg leveringsmetode;
|Sælger|
:Opret ordre;
|Lager|
:Ordre]
:Pak ordre;
:Send ordre til kunde;
else (no)
endif

|Kunde|
stop



@enduml
