@startuml
'https://plantuml.com/object-diagram


object user{
    firstname
    lastname
    email
    zipcode
    address
    phone
    password
    admin?
}



object carport{
    carportwidth
    carportlength
    carportheight
    roofmaterial

}
object shed{
    shedwidth
    shedlength
}

object order{
    ordernumber
    orderdate
    orderstatus
    comment
    orderprice
}




user "1"--"*" order
order "1"-- "1" carport
carport "1"-- "1"shed



@enduml
