@startuml
'https://plantuml.com/object-diagram


object customer{
    name
    email
    address
    phone
    town
    postcode
    password
}

object employee{
    name
    email
    password
}


object carport{
    carportwidth
    carportlength
    carportheight
    roofmaterial
    carportprice

}
object shed{
    shedwidth
    shedlength
}

object order{
    ordernumber
    orderdate
    orderstatus
    orderprice
}




customer "1"--"*" order
order "1"-- "1"carport
employee "1"--"*" order
carport "1"-- "1"shed



@enduml
